"""add_holidays_and_projects

Revision ID: 0ef7f79a411d
Revises: 9e8d19e598ae
Create Date: 2026-05-10 10:32:35.004073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '0ef7f79a411d'
down_revision: Union[str, Sequence[str], None] = '9e8d19e598ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('holidays',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('holiday_no', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('shift', sa.Enum('all_shifts', 'day_shift', 'night_shifts', name='holidayshift'), nullable=False),
    sa.Column('holiday_date', sa.Date(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('holiday_type', sa.Enum('national', 'religious', 'cultural', 'awareness', 'environmental', name='holidaytype'), nullable=False),
    sa.Column('status', sa.Enum('pending', 'approved', name='holidaystatus'), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('tag', sa.Enum('web', 'android', 'ios', 'backend', 'testing', 'design', name='projecttag'), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('team_leader', sa.String(length=120), nullable=False),
    sa.Column('priority', sa.Enum('low', 'medium', 'high', name='projectpriority'), nullable=False),
    sa.Column('status', sa.Enum('new', 'running', 'finished', 'on_hold', name='projectstatus'), nullable=False),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('comments_count', sa.Integer(), nullable=False),
    sa.Column('bugs_count', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('projects')
    op.drop_table('holidays')
    # ### end Alembic commands ###
