"""initial_schema

Revision ID: 24e849490812
Revises: 69e8d5891df9
Create Date: 2026-05-07 10:22:40.575087

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa



revision: str = '24e849490812'
down_revision: Union[str, Sequence[str], None] = '69e8d5891df9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
